### ISSUE TITLE
Age-field    - Players search(Taking String and large values)

### ISSUE THREAD

**Issue by Adib-shadman** [GrantUpson/Sports-CMS#75]
‘Age’ field is taking varchar values, I think it should be only numbers (after decimal, I think only one digit should be allowed).  In the age field, the user can type large numbers which does not represents anyone’s age at all. I think It should be in a range. Let’s say age (0-120).

**Comment by GrantUpson** [comment]
It will no longer process nonintegers. as it's not a form it cant tell the user outright to change it since its submitted with javascript. At this point it's not worth investing any more time in it than that.
