### ISSUE TITLE
Tournament Director page - Multiple bugs

### ISSUE THREAD

**Issue by mjginaus** [GrantUpson/Sports-CMS#88]
1. New Tournament Directors should not be able to access Club Management/members/recent club events without first creating a club
2. Creating a club does not allow numbers to be used in their names
3. Edit Personal Information does not work (for Test@user.com) - it doesn't update
4. After creating a club, you can remove yourself - this means you cannot get back into your club if no other TD is assigned to it (may not be a bug)
5. If you have removed yourself from a club you have created, you are able recreate it with the exact same name (duplicate club issue?)
6. You cannot add a player whose e-mail has already been used - however the system doesn't tell you about that error, it just wont add them
7. Adding a new player in "club members" creates a player with a ranking of 0 (is this an issue?)
8. Dates showing in the incorrect format (Y/M/D)
9. It is not possible to remove players from the club, only edit them

**Comment by GrantUpson** [comment]
1. TODO
2. Not a bug.
3. TODO
4. Not a bug.
5. Clubs may have the same names, this is an administrative issue that an admin will need to help with.
6. There is now a button for adding existing players in the system to a club and adding a new player that doesn't exist, making this issue void.
7. Working as intended as players cannot be shown if they don't have a rating.
8. Y/M/D is the correct format and is used throughout the entire website.
9. Solved.

**Comment by watkinsj** [comment]
3. complete
